version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: Godot
    ports:
      - '5432:5432'
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
